name: Deploy Staging (Tag & Version Only)

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from release branch
        id: version
        run: |
          VERSION="${GITHUB_REF##*/}"

          if [[ -z "$VERSION" ]]; then
            echo "❌ Invalid release branch"
            exit 1
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Simulate build staging image
        run: |
          IMAGE_TAG="v${{ steps.version.outputs.version }}-staging"
          echo "docker build -t test-app:$IMAGE_TAG ."
          echo "✅ STAGING IMAGE TAG = test-app:$IMAGE_TAG"

      - name: Create git staging tag
        run: |
          TAG="v${{ steps.version.outputs.version }}-staging"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag -a "$TAG" -m "Staging release $TAG"
          git push origin "$TAG"
